version: "3.3"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    network_mode: bridge
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
    volumes:
      - ./mysql_data/logs:/var/log/mysql
      - ./mysql_data/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1
    restart: always
  consul:
    image: consul
    container_name: consul
    network_mode: bridge
    ports:
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
      - 8500:8500
      - 53:53/udp
    volumes:
      - ./consul_data/data:/consul/data
      - ./consul_data/config:/consul/config
    restart: always
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    network_mode: bridge
    ports:
      - 15672:15672
      - 5672:5672
  elasticsearch:
    image: elasticsearch:6.8.0
    container_name: elasticsearch
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
  skywalking:
    image: apache/skywalking-oap-server
    container_name: skywalking
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
      - 1234:1234
    links:
      - elasticsearch
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
  skywalkingui:
    image: apache/skywalking-ui
    container_name: skywalkingui
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
    links:
      - skywalking
    environment:
      SW_OAP_ADDRESS: skywalking:12800
    depends_on:
      - skywalking
