// <auto-generated />

using CoreShopUms.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CoreShopUms.Migrations
{
    [DbContext(typeof(UmsContext))]
    internal class UmsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreShopUms.Infrastructure.Entity.User", b =>
            {
                b.Property<string>("Id")
                    .HasColumnName("Id")
                    .HasColumnType("varchar(50)");

                b.Property<string>("Account")
                    .HasColumnType("varchar(50)");

                b.Property<string>("Password")
                    .HasColumnType("varchar(300)");

                b.Property<string>("RealName")
                    .HasColumnType("varchar(50)");

                b.HasKey("Id");

                b.ToTable("Users");
            });
#pragma warning restore 612, 618
        }
    }
}